[package]
name    = "rusting-bitmaps"
version = "0.1.0"
authors = ["Techgeek1"]
edition = "2018"

[dev-dependencies]
criterion   = "0.2.11"
num-traits  = "0.2.8"
rand        = { version = "0.7.0", features = ["small_rng"] }

[[bench]]
name    = "queries"
harness = false